### ISSUE TITLE
Hi my name is tobikoer

### ISSUE THREAD

**Issue by tobikoer** [EarthPol/EPMCIssues#72]
### Is your suggestion related to a problem? Please describe below.

Hi mob rates very bad cannot find any even with 80 players online.

### Describe the solution you'd like

Uh if u can add more mobs.

**Comment by 0xBitMC** [comment]
@tobikoer,

You need to use this form properly or you'll be prevented from using it in the future. If you have a suggestion, please accurately name your titles etc for your postings as such.

Since you have made this post, I have adjusted mob spawn rates and fixed our plugin to allow mob spawning to work at a higher mspt.

So this issue is considered resolved.
